SET AUTOCOMMIT OFF;
CREATE TABLE R(A INT, B INT, C FLOAT, D VARCHAR, E DATETIME);
CREATE TABLE S(A INT, B INT, C INT, D FLOAT, E VARCHAR, F VARCHAR);
SELECT R.A, COUNT(1) FROM R, S GROUP BY R.A HAVING COUNT(1) > 1;
ROLLBACK;
